// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ClassInstructor string
	ClassStudent    string
	Classes         string
	Departments     string
	Staffs          string
	Students        string
}{
	ClassInstructor: "class_instructor",
	ClassStudent:    "class_student",
	Classes:         "classes",
	Departments:     "departments",
	Staffs:          "staffs",
	Students:        "students",
}
